server:
  port: 8741
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
eureka:
  client:
    service-url:
#      defaultZone: http://admin:admin@116.62.127.60:8761/eureka/
#      defaultZone: http://admin:admin@localhost:8761/eureka/
      defaultZone: http://admin:admin@13.211.205.147:8761/eureka/
#      13.210.241.197
#  instance:
#    ip-address: localhost
#    prefer-ip-address: true
spring:
  application:
    name: provider-quote-syx-test
#    name: provider-quote-prod

#  rabbitmq:
#      host: 13.211.205.147
#      port: 5672
#      username: admin
#      password: digiccy@123
#  cloud:
#    stream:
#      bindings:
#        output:
#          destination: greeting
#          producer:
#            partitionKeyExpression: payload
#            partitionCount: 2
  redis:
    database: 2
#    host: 127.0.0.1
#    port: 6379
#    password: root
    host: 116.62.127.60
    port: 6389
    password: szhb_dev888
    timeout: 20000
#    cluster: #配置其他的redis服务
#      nodes: 127.0.0.1:6389,127.0.0.1:6399
#      max-redirects: 6
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1

  datasource:
    username: root
    password: oxchains123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.62.127.60:3306/oxchains_dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    dbcp2:
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 2


######################## mapper插件
mybatis:
    type-aliases-package: com.mi.hundsun.oxchains.base.core.tx.po
    configuration:
      map-underscore-to-camel-case: true # 数据库开启驼峰转换
mapper:
    mappers:
        - com.mi.hundsun.oxchains.base.common.baseMapper.QueryMapper
        - com.mi.hundsun.oxchains.base.common.baseMapper.InsertMapper
        - com.mi.hundsun.oxchains.base.common.baseMapper.UpdateMapper
        - com.mi.hundsun.oxchains.base.common.baseMapper.DeleteMapper
    not-empty: false
    identity: MYSQL
#----------------------- mapper插件 end