server:
  port: 8120
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
eureka:
  client:
    service-url:
#           defaultZone: http://admin:admin@116.62.127.60:8761/eureka/
#           defaultZone: http://admin:admin@localhost:8761/eureka/
           defaultZone: http://admin:admin@13.211.205.147:8761/eureka/
  instance:
    #本机ip
    ip-address: localhost
    #使用ip向注册中心注册
    prefer-ip-address: true
spring:
  application:
    name: consumer-quote-syx-test
  rabbitmq:
    host: 13.211.205.147
    port: 5672
    username: admin
    password: digiccy@123
#    host: 13.211.205.147
#    port: 5672
#    username: admin
#    password: digiccy@123

######################## redis
    # Redis数据库索引（默认为0）
  redis:
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: root
    # 连接超时时间（毫秒）
    timeout: 2000
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 2000
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 5
    # 连接池中的最大空闲连接
      max-idle: 200
    # 连接池中的最小空闲连接
      min-idle: 100
#------------------------ redis end

## hystrix 监控  只对加了@HystrixCommand注解的方法起作用。

feignSuffix: syx-test
#feignSuffix: prod
bianQuoteFeignName: digiccy-hq-bian
okexQuoteFeignName: digiccy-hq-okex
huobiQuoteFeignName: digiccy-hq-huobi
bitQuoteFeignName: digiccy-hq-bitfinex

