server:
  port: 8130
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    service-url:
     #defaultZone: http://admin:admin@13.211.205.147:8761/eureka/
#      defaultZone: http://admin:admin@116.62.127.60:8761/eureka/
     defaultZone: http://admin:admin@localhost:8761/eureka/

spring:
  application:
    name: consumer-admin-fangyong-test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 时间返回格式化
    time-zone: GMT+8
  resources:
    static-locations: classpath:/webapp/base/


######################### freemarker
  freemarker:
    check-template-location: false
  http:
    multipart:
      max-file-size: 8MB #限制默认文件上传大小
      max-request-size: 8MB #限制默认文件上传大小
  mvc:
    favicon:
      enabled: false
#------------------------ freemarker end
######################## redis
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
# Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: 192.168.2.84
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 2000
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 200
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 5
    # 连接池中的最大空闲连接
      max-idle: 20
    # 连接池中的最小空闲连接
      min-idle: 10
#------------------------ redis end

######################### 日志
logging:
  config: classpath:config/logback-spring.xml
#------------------------ 日志end


# 本地参数配置
com:
  mi:
    kaptcha:
      border: 'no'
      border.color: 105,179,90
      textproducer.font.color: 238,238,238
      image.width: 100
      image.height: 38
      textproducer.font.size: 30
      session.key: code
      background.clear.from: 50,50,50
      background.clear.to: 50,50,50
      textproducer.char.length: 4
      textproducer.font.names: Arial
      textproducer.char.string: abcde2345678gfymnpwx
      noise.impl: com.google.code.kaptcha.impl.NoNoise
      obscurificator.impl: com.google.code.kaptcha.impl.Simple

feignSuffix: fangyong-test

#feignSuffix: prod
bianTradeFeignName: DIGICCY-TRADE-BIAN
okexTradeFeignName: DIGICCY-TRADE-OKEX
huobiTradeFeignName: DIGICCY-TRADE-HUOBI
bitTradeFeignName: DIGICCY-TRADE-BITFINEX


info:
  app.name: consumer-admin
  company.name: hckj
  build.artifactId: ${project.artifactId}
  build.version:  ${project.version}