server:
  port: 8771
ribbon:
  ReadTimeout: 1200000
#请求连接的超时时间
  ConnectTimeout: 120000
eureka:
  client:
    service-url:
      default-zone: http://admin:admin@localhost:8761/eureka/
#      default-zone: http://admin:admin@119.23.57.169:8761/eureka/
#      default-zone: http://admin:admin@13.211.205.147:8761/eureka/
#      instance:
#          ip-address: localhost
#          prefer-ip-address: true
      eureka-server-connect-timeout-seconds: 30
      eureka-server-read-timeout-seconds: 30
spring:
  application:
    name: provider-trade-fangyong-test
#    name: provider-trade-prod

  #################### DataSource Start ####################
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oxchains_tx_dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    #url: jdbc:mysql://116.62.127.60:3306/oxchains_tx1_dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    dbcp2:
    # 连接池中的最大空闲连接
      max-idle: 8
    # 连接池中的最小空闲连接
      min-idle: 1
      initial-size: 5
      max-total: 20
      max-wait-millis: 60000
  #################### DataSource End ####################
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      txSyncExchange: txSyncExchange-dev
      subDelegateQueue: tx_sync_sub_message-dev
      mainDelegateFailureQueue: main-delegate-failure-queue-dev
      revokeDelegateSuccessQueue: revoke-delegate-failure-queue-dev
      subDelegateSuccessQueue: sub-delegate-success-queue-dev
      subDelegateFailureQueue: sub-delegate-failure-queue-dev
  redis:
    database: 0
    host: 192.168.2.84
    port: 6379
    password:
    timeout: 20000
#    cluster: #配置其他的redis服务
#      nodes: 127.0.0.1:6389,127.0.0.1:6399
#      max-redirects: 6
    pool:
      max-active: 200
      min-idle: 5
      max-idle: 20
      max-wait: 10

######################## mapper插件
mybatis:
    type-aliases-package: com.mi.hundsun.oxchains.base.core.tx.po
    configuration:
      map-underscore-to-camel-case: true # 数据库开启驼峰转换
mapper:
    mappers:
        - com.mi.hundsun.oxchains.base.common.baseMapper.QueryMapper
        - com.mi.hundsun.oxchains.base.common.baseMapper.InsertMapper
        - com.mi.hundsun.oxchains.base.common.baseMapper.UpdateMapper
        - com.mi.hundsun.oxchains.base.common.baseMapper.DeleteMapper
    not-empty: false
    identity: MYSQL
#----------------------- mapper插件 end

#--------------- 定时器配置-------start
txSyncSubDelegateCron: 0/1 * * * * *
txSyncMainDelegateCron: 0/1 * * * * *
# 每天晚上23:59:59秒触发一次
cronCountTransInfo: 59 59 23 * * ?
cronCountTransServiceInfo: 59 59 23 * * ?
#--------------- 定时器配置-------end

feignSuffix: fangyong-test
#feignSuffix: prod

info:
  app.name: provider-trade
  company.name: hckj
  build.artifactId: ${project.artifactId}
  build.version:  ${project.version}

bianTradeFeignName: DIGICCY-TRADE-BIAN
huobiTradeFeignName: DIGICCY-TRADE-HUOBI
okexTradeFeignName: DIGICCY-TRADE-OKEX-BAFFLE
bitTradeFeignName: DIGICCY-TRADE-BITFINEX-BAFFLE

bianQuoteFeignName: digiccy-hq-bian
okexQuoteFeignName: digiccy-hq-okex
huobiQuoteFeignName: digiccy-hq-huobi
bitQuoteFeignName: digiccy-hq-bitfinex